### ISSUE TITLE
[Question] Differences with respect to --watchFileChanges=true cypress config option

### ISSUE THREAD

**Issue by vikikamath** [TheBrainFamily/cypress-app-watcher-preprocessor#5]
How different is the behavior of this module from
`cypress run --config watchForFileChanges=true`
`cypress open --config watchForFileChanges=true`

**Comment by lgandecki** [comment]
Hello @vikikamath . Thank for checking. This one reruns when you app - be it either backed, frontend or both - reloads. The Cypress built in watcher only rerun when your test files change
